---

- name: Install nginx Packages
  apt: name={{ packages_nginx }} state=present update_cache=yes

- name: Create web root
  file: path={{ nginx_root }} state=directory

- name: Install index.html
  template: src=templates/htdocs/index.html.j2 dest={{ nginx_root }}/index.html mode=755

- name: Install nginx configuration
  template: src=templates/nginx/sites-available/stel.j2
            dest=/etc/nginx/sites-available/stel
  notify: Reload nginx

- name: Activate nginx configuration
  file: src=/etc/nginx/sites-available/stel
        dest=/etc/nginx/sites-enabled/stel state=link
  notify: Reload nginx

- name: Remove default nginx configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: Reload nginx

- name: Flush handlers
  meta: flush_handlers
