---

# nginx base setup test project

- name: Set up demo nginx server on AWS
  become: False
  hosts: localhost
  connection: local
  gather_facts: False
  any_errors_fatal: yes
  vars_files:
    - "conf/default.yml"

  roles:
    - role: aws/create-instance

  tasks:
  - name: Wait for SSH to come up
    wait_for: host={{ item.public_ip }} port=22 delay=1 timeout=480 state=started
    with_items: "{{ ec2.instances }}"    

  - name: Update hosts list
    add_host: hostname={{ item.public_ip }} groups=ec2hosts
    with_items: "{{ ec2.instances }}"

- hosts: ec2hosts
  become: True
  name: nginx setup
  vars_files:
    - "conf/default.yml"
  user: "{{ ec2_user }}"
  gather_facts: true


  roles:
    - role: nginx
    
  tasks:

  - name: Verify nginx is running
    service: name=nginx state=started enabled=yes

  - name: Get index page from server
    action: uri url=http://{{ inventory_hostname }} return_content=yes
    register: webpage

  - fail: msg='Index page is incorrect'
    when: "'Automation for the People' not in webpage.content"
      
  - name: debug web server
    debug:
      msg: "Browse to http://{{ inventory_hostname }} to verify"

