---

- name: Create security group if needed
  ec2_group:
    name: demosecurity
    description: Demo security group with http and ssh access only
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  when: ec2_security_groups == none
  register: ec2_group

- name: Set ec2_security_groups variable
  set_fact: ec2_security_groups="{{ ec2_group.group_id }}"
  when: ec2_security_groups == none

- name: new secgrp
  debug:
    var: ec2_group
    
- name: Provision a single instance for nginx
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ ec2_region }}"
    key_name: "{{ ec2_key_name }}"
    group_id: "{{ ec2_security_groups }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami }}"
    wait: true
    exact_count: 1
    count_tag:
      Name: "{{ ec2_instance_tag }}"
    instance_tags:
      Name: "{{ ec2_instance_tag }}"
  register: ec2

- name: Update hosts list
  add_host: hostname={{ item.public_ip }} groups=ec2hosts
  with_items: "{{ ec2.instances }}"
