---

#------------------------------------------------------------------------------
# Three configuration variables are required to be modified for
# your environment.
#
# They are ec2_access_key, ec2_secret_key, and aws_key_name
#
# The remainder of the variables are optional.
#------------------------------------------------------------------------------

# Replace the following two values with your AWS credentials
aws_access_key: YOUR_ACCESS_KEY_HERE
aws_secret_key: YOUR_SECRET_KEY_HERE

# A key pair is required to access AWS resources.  This key can be created in
# AWS directly via console, or created independently and imported into AWS.
# For more information, refer to the Amazon AWS documentation found here:
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html
ec2_key_name: YourKeyHere

#------------------------------------------------------------------------------
# Config options below this line are optional
#------------------------------------------------------------------------------

ec2_instance_tag: Web Demo

ec2_region: us-east-1

# Security group list, optional.
# If blank, will create a new security group with SSH (22) and HTTP (80) open. 
ec2_security_groups:
# example:
#  - sg-a7ff12db
#  - sg-1d914576
#  - sg-270fed5b

ec2_instance_type: t1.micro

# Ubuntu Server 14.04 LTS
ec2_ami: ami-a95044be

# Different linux flavors have different default users on ec2.
# Ubuntu uses the `ubuntu` user, whereas CentOS and Amazon Linux, use ec2-user
ec2_user: ubuntu
